[package]
name = "instruction"
version = "0.1.0"
edition = "2021"

[lib]
name = "instruction"
crate-type = ["cdylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.10.3"
solana-program = "1.15.2"
